name: Main
version: '${project.version}'
main: com.articreep.surfaces.surfaces.Main
api-version: 1.18
authors: [ Arti_Creep ]
description: Properties that can be applied to block surfaces, causing them to interact differently with other blocks
